export const products = [
  {
    "id": 1,
    "product_name": "Refrigerator",
    "price": 157.17,
    "quantity": 21,
    "category": "electronics",
    "brand": "Realcube",
    "description": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "release_date": "7/11/2014",
    "rating": 2.9,
    "color": "Fuscia",
    "size": "medium",
    "webcategorySlug": "electronics"
  },
  {
    "id": 2,
    "product_name": "Honorable",
    "price": 316.37,
    "quantity": 85,
    "category": "home goods",
    "brand": "Skyba",
    "description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "release_date": "11/27/2017",
    "rating": 3.9,
    "color": "Violet",
    "size": "medium",
    "webcategorySlug": "home-goods"
  },
  {
    "id": 3,
    "product_name": "Musclemass",
    "price": 728.27,
    "quantity": 67,
    "category": "supplements",
    "brand": "Yata",
    "description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    "release_date": "6/12/2010",
    "rating": 3.3,
    "color": "Purple",
    "size": "small",
    "webcategorySlug": "supplements"
  },
  {
    "id": 4,
    "product_name": "Mrs",
    "price": 272.9,
    "quantity": 16,
    "category": "home goods",
    "brand": "Tagtune",
    "description": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    "release_date": "2/24/2014",
    "rating": 2.0,
    "color": "Purple",
    "size": "small",
    "webcategorySlug": "home-goods"
  },
  {
    "id": 5,
    "product_name": "Growth hormones",
    "price": 38.68,
    "quantity": 15,
    "category": "growth",
    "brand": "Devpoint",
    "description": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "release_date": "10/13/2019",
    "rating": 3.4,
    "color": "Teal",
    "size": "small",
    "webcategorySlug": "growth"
  },
  {
    "id": 6,
    "product_name": "Rev",
    "price": 731.69,
    "quantity": 83,
    "category": "home goods",
    "brand": "Mymm",
    "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    "release_date": "5/16/2013",
    "rating": 1.6,
    "color": "Crimson",
    "size": "small",
    "webcategorySlug": "home-goods"
  },
  {
    "id": 7,
    "product_name": "Mr",
    "price": 890.1,
    "quantity": 2,
    "category": "health",
    "brand": "Gabtype",
    "description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    "release_date": "2/8/2012",
    "rating": 1.9,
    "color": "Purple",
    "size": "extra large",
    "webcategorySlug": "growth"
  },
  {
    "id": 8,
    "product_name": "Dr",
    "price": 459.73,
    "quantity": 83,
    "category": "clothing",
    "brand": "Skyba",
    "description": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    "release_date": "12/15/2015",
    "rating": 2.2,
    "color": "Goldenrod",
    "size": "extra large",
    "webcategorySlug": "clothing"
  },
  {
    "id": 9,
    "product_name": "Dr",
    "price": 680.03,
    "quantity": 24,
    "category": "beauty",
    "brand": "Jaxworks",
    "description": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "release_date": "7/20/2021",
    "rating": 3.4,
    "color": "Mauv",
    "size": "large",
    "webcategorySlug": "beauty"
  },
  {
    "id": 10,
    "product_name": "sunscreen",
    "price": 598.02,
    "quantity": 64,
    "category": "beauty",
    "brand": "Fivechat",
    "description": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "release_date": "7/28/2015",
    "rating": 3.9,
    "color": "Crimson",
    "size": "large",
    "webcategorySlug": "beauty"
  },
  {
    "id": 11,
    "product_name": "toaster",
    "price": 484.15,
    "quantity": 92,
    "category": "electronics",
    "brand": "Twitterwire",
    "description": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    "release_date": "9/6/2013",
    "rating": 2.0,
    "color": "Blue",
    "size": "extra large",
    "webcategorySlug": "electronics"
  },
  {
    "id": 12,
    "product_name": "Rev",
    "price": 744.0,
    "quantity": 27,
    "category": "clothing",
    "brand": "Oba",
    "description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "release_date": "9/23/2020",
    "rating": 4.6,
    "color": "Red",
    "size": "large",
    "webcategorySlug": "clothing"
  },
  {
    "id": 13,
    "product_name": "silk saree",
    "price": 727.93,
    "quantity": 19,
    "category": "clothing",
    "brand": "Brainlounge",
    "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    "release_date": "1/9/2011",
    "rating": 4.5,
    "color": "Green",
    "size": "large",
    "webcategorySlug": "clothing"
  },
  {
    "id": 14,
    "product_name": "Revitalize",
    "price": 255.65,
    "quantity": 42,
    "category": "electronics",
    "brand": "Coxwire",
    "description": "Curabitur pretium, neque a condimentum mollis, orci lectus faucibus ante, at suscipit lorem eros ac erat. Aenean at risus id ligula vestibulum scelerisque.",
    "webcategorySlug": "electronics"
  },
  {
    "id": 15,
    "product_name": "lotion",
    "price": 598.02,
    "quantity": 64,
    "category": "beauty",
    "brand": "Fivechat",
    "description": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "release_date": "7/28/2015",
    "rating": 3.9,
    "color": "Crimson",
    "size": "large",
    "webcategorySlug": "beauty"
  },
  {
    "id": 16,
    "product_name": "iron",
    "price": 484.15,
    "quantity": 92,
    "category": "electronics",
    "brand": "Twitterwire",
    "description": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    "release_date": "9/6/2013",
    "rating": 2.0,
    "color": "Blue",
    "size": "extra large",
    "webcategorySlug": "electronics"
  },
  {
    "id": 17,
    "product_name": "cotton shawl",
    "price": 744.0,
    "quantity": 27,
    "category": "clothing",
    "brand": "Oba",
    "description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "release_date": "9/23/2020",
    "rating": 4.6,
    "color": "Red",
    "size": "large",
    "webcategorySlug": "clothing"
  },
  {
    "id": 18,
    "product_name": "silk saree",
    "price": 727.93,
    "quantity": 19,
    "category": "clothing",
    "brand": "Brainlounge",
    "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    "release_date": "1/9/2011",
    "rating": 4.5,
    "color": "Green",
    "size": "large",
    "webcategorySlug": "clothing"
  },
  {
    "id": 19,
    "product_name": "Revitalize",
    "price": 255.65,
    "quantity": 42,
    "category": "elronics",
    "brand": "Coxwire",
    "description": "Curabitur pretium, neque a condimentum mollis, orci lectus faucibus ante, at suscipit lorem eros ac erat. Aenean at risus id ligula vestibulum scelerisque.",
    "webcategorySlug": "elronics"
  },
  {
    "id": 19,
    "product_name": "Revitalize",
    "price": 255.65,
    "quantity": 42,
    "category": "elronics",
    "brand": "Coxwire",
    "description": "Curabitur pretium, neque a condimentum mollis, orci lectus faucibus ante, at suscipit lorem eros ac erat. Aenean at risus id ligula vestibulum scelerisque.",
    "webcategorySlug": "elronics"
  },
  {
    "id": 19,
    "product_name": "Revitalize",
    "price": 255.65,
    "quantity": 42,
    "category": "ronics",
    "brand": "Coxwire",
    "description": "Curabitur pretium, neque a condimentum mollis, orci lectus faucibus ante, at suscipit lorem eros ac erat. Aenean at risus id ligula vestibulum scelerisque.",
    "webcategorySlug": "ronics"
  },
  {
    "id": 19,
    "product_name": "Revitalize",
    "price": 255.65,
    "quantity": 42,
    "category": "electros",
    "brand": "Coxwire",
    "description": "Curabitur pretium, neque a condimentum mollis, orci lectus faucibus ante, at suscipit lorem eros ac erat. Aenean at risus id ligula vestibulum scelerisque.",
    "webcategorySlug": "electros"
  },
  {
    "id": 19,
    "product_name": "Revitalize",
    "price": 255.65,
    "quantity": 42,
    "category": "elect",
    "brand": "Coxwire",
    "description": "Curabitur pretium, neque a condimentum mollis, orci lectus faucibus ante, at suscipit lorem eros ac erat. Aenean at risus id ligula vestibulum scelerisque.",
    "webcategorySlug": "elect"
  }
]
